service: notion-to-text

provider:
    name: aws
    runtime: nodejs14.x
    memorySize: 1024
    timeout: 30
    lambdaHashingVersion: "20201221"

functions:
    notion-to-text-function:
        handler: index.handler
        environment:
            DEBUG: 0

package:
    exclude:
        - node_modules/puppeteer/.local-chromium/**

custom:
    chrome:
        flags:
            - --window-size=1920,1080
            - --hide-scrollbars
            #- --ignore-certificate-errors
        functions:
            - notion-to-text-function
